import { Images } from '../assets';


export const MovieData: MovieRecordType = {
  XMen: {
    title: 'XMen',
    description: '2014 | Action | Fiction',
    isFavorite: false,
    isTrending: true,
    image: Images.XMen,
  },
  Avenger: {
    title: 'Avenger',
    description: '2014 | Action | Fiction',
    image: Images.Avenger,
    isFavorite: false,
    isTrending: true,
  },
  BlackAdams: {
    title: 'BlackAdams',
    description: '2022 | Action | Fiction',
    image: Images.BlackAdam,
    isFavorite: false,
    isTrending: true,
  },
  WonderWomen: {
    title: 'WonderWomen | Action | Fiction',
    description: '2016',
    image: Images.WonderWomen,
    isFavorite: false,
    isTrending: false,
  },
  WonderWomen2: {
    title: '',
    description: '2018 | Action | Fiction',
    image: Images.WonderWomen2,
    isFavorite: false,
    isTrending: false,
  },
  Alone: {
    title: 'Alone',
    description: '2019 | Thriller',
    image: Images.Alone,
    isFavorite: false,
    isTrending: false,
  },
  AnimatedSeries: {
    title: 'Animated Series',
    description: '2019 | Animated',
    image: Images.AnimatedSeries,
    isFavorite: false,
    isTrending: false,
  },
  BlackWidow: {
    title: 'BlackWidow',
    description: '2022 | Action | Fiction',
    image: Images.BlackWidow,
    isFavorite: false,
    isTrending: false,
  },
  BlackWidowMovie: {
    title: 'BlackWidowMovie',
    description: '2023 | Action | Fiction',
    image: Images.BlackWidowMovie,
    isFavorite: false,
    isTrending: false,
  },
  Buckey: {
    title: 'Buckey',
    description: '2019 | Action | Fiction',
    image: Images.Buckey,
    isFavorite: false,
    isTrending: false,
  },
  Danav: {
    title: 'Danav',
    description: '2023 | Action | Horror | Fiction',
    image: Images.Danav,
    isFavorite: false,
    isTrending: false,
  },
  DeadPool: {
    title: 'DeadPool',
    description: '2015 | Action | Fiction',
    image: Images.DeadPool,
    isFavorite: false,
    isTrending: true,
  },
  DeadPool2: {
    title: 'DeadPool2',
    description: '2017 | Action | Fiction',
    image: Images.DeadPool2,
    isFavorite: false,
    isTrending: true,
  },
  DeadPool3: {
    title: 'DeadPool3',
    description: '2019 | Action | Fiction',
    image: Images.DeadPool3,
    isFavorite: false,
    isTrending: true,
  },
  Force: {
    title: 'Force',
    description: '2018 | Action',
    image: Images.Force,
    isFavorite: false,
    isTrending: false,
  },
  Frozen: {
    title: 'Frozen',
    description: '2021 | Animated',
    image: Images.Frozen,
    isFavorite: false,
    isTrending: false,
  },
  GardianofGalaxyVol1: {
    title: 'Galaxy of Galaxy Vol',
    description: '2011 | Action | Fiction',
    image: Images.GardianofGalaxyVol1,
    isFavorite: false,
    isTrending: true,
  },
  GardianofGalaxyVol2: {
    title: 'Galaxy of Galaxy Vol',
    description: '2011 | Action | Fiction',
    image: Images.GardianofGalaxyVol2,
    isFavorite: false,
    isTrending: true,
  },
  GardianofGalaxyVol3: {
    title: 'Galaxy of Galaxy Vol',
    description: '2011 | Action | Fiction',
    image: Images.GardianofGalaxyVol3,
    isFavorite: false,
    isTrending: true,
  },
  HellBoy: {
    title: 'Hell Boy',
    description: 'Action | Fiction',
    image: Images.HellBoy,
    isFavorite: false,
    isTrending: true,
  },
  InfinityWar: {
    title: 'Infinity War',
    description: '2020',
    image: Images.InfinityWar,
    isFavorite: false,
    isTrending: true,
  },
  InterStellar: {
    title: 'InterStellar',
    description: '2018 | Adventure',
    image: Images.InterStellar,
    isFavorite: false,
    isTrending: true,
  },
  JurassicPark: {
    title: '',
    description: '',
    image: Images.JurasiccPark,
    isFavorite: false,
    isTrending: false,
  },
  JusticeLeague: {
    title: 'Justice League',
    description: '',
    image: Images.JustisLegue,
    isFavorite: false,
    isTrending: true,
  },
  KingKong: {
    title: 'King KONG',
    description: '2018 | Adventure',
    image: Images.KingKong,
    isFavorite: false,
    isTrending: true,
  },
  MsMarwel: {
    title: 'Ms Marwel',
    description: '2018 | Action',
    image: Images.MsMarwel,
    isFavorite: false,
    isTrending: true,
  },
  Soldier: {
    title: 'King KONG',
    description: '2018 | Action',
    image: Images.Solder,
    isFavorite: false,
    isTrending: true,
  },
  SpiderMan: {
    title: 'Spiderman',
    description: '2018 | Action | Fiction',
    image: Images.SpiderMan,
    isFavorite: false,
    isTrending: true,
  },
  Transformer: {
    title: 'Transformer',
    description: '2019 | Action | Fiction',
    image: Images.Transformer,
    isFavorite: false,
    isTrending: true,
  },
  TugOfWar: {
    title: 'Tug Of War',
    description: '2017 | Action',
    image: Images.TugOfWar,
    isFavorite: false,
    isTrending: false,
  },
  Vampire: {
    title: 'Vampire',
    description: '2017 | Action',
    image: Images.Vampire,
    isFavorite: false,
    isTrending: false,
  },
  Venom: {
    title: 'Venom',
    description: '2017 | Action',
    image: Images.Venom,
    isFavorite: false,
    isTrending: true,
  },
  War: {
    title: 'War',
    description: '2022 | Action',
    image: Images.War,
    isFavorite: false,
    isTrending: false,
  },
  WitchHunter: {
    title: 'Witch Hunter',
    description: '2017 | Action',
    image: Images.WitchHunter,
    isFavorite: false,
    isTrending: false,
  },
};
